### ISSUE TITLE
Tool Visibility - VM MDSheet 

### ISSUE THREAD

**Issue by egmulky** [SoftwareEngineeringToolDemos/ICSE-2012-MDSheet#12]
Tool is not immediately visible as soon as the VM is started. Please specify if you have been granted permission for that in response to this issue.

**Comment by hmansari** [comment]
As the user should open "Libreoffice calc" for using the tool from the command line by going to a specific directory where I have compiled the source code, I have written a script "open.sh" and put it in "Startup Applications". Now, the user can just start using the tool without any extra steps needed to open the Libreoffice calc.
