### ISSUE TITLE
Tool closed multiple times while working - VM MDSheet

### ISSUE THREAD

**Issue by egmulky** [SoftwareEngineeringToolDemos/ICSE-2012-MDSheet#14]
While working on the tool, the tool closed prematurely multiple times when my work was half done. I donot understand what the issue was, but i had to repeat the steps multiple times due to this.

**Comment by manish211** [comment]
@egmulky Can you please assign this either to yourself or haris?

**Comment by hmansari** [comment]
The tool has a lot of dependencies. I am trying to fix it, but due to some incompatibilities with the LibreOffice, the tool shuts down amid working on the spreadsheet.
