### ISSUE TITLE
No source code

### ISSUE THREAD

**Issue by egmulky** [SoftwareEngineeringToolDemos/ICSE-2012-MDSheet#7]
Repository does not contain source code (Mentioned to comply with rubric)

**Comment by hmansari** [comment]
I already mentioned in the README that the source code is not available publicly and also "The author has private repositories for the source code which can only be shared by contacting the author, Dr. Jorge Mendes."

**Comment by egmulky** [comment]
Yes, had to mention the issue as the professor's rubric states this example, if you have an issue that says you have not included the source code, and the source code was not made available by the authors, in a comment on the issue say "The source code is not available on the internet and was not provided by the authors." We have to create an issue even for this case.
